function plant = plant_block(u, q_p)
%PLANT_BLOCK
%    PLANT = PLANT_BLOCK(U_1,U_2,X_3,X_4,X_5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    21-May-2020 20:45:52

    u_1 = u(1);
    u_2 = u(2);
    
    x_1 = q_p(1);
    x_2 = q_p(2);
    x_3 = q_p(3);
    x_4 = q_p(4);
    x_5 = q_p(5);
    
    plant = [x_4.*cos(x_3);...
             x_4.*sin(x_3);...
             x_5;...
             u_1.*-5.0e1-u_2.*5.0e1;
             u_1.*-8.0e3+u_2.*8.0e3];
