function [q, p, pp] = generalized_variables(mechanism, q_bullet, qp_bullet)
    % Speed to derivative coordinates conversion
    D_bullet = subs(mechanism.eqdyn.D_bullet, ...
                    mechanism.eqdyn.q_bullet, ...
                    q_bullet);
    
    Dp_bullet = subs(mechanism.eqdyn.Dp_bullet, ...
                     [mechanism.eqdyn.q_bullet, ...
                      mechanism.eqdyn.qp_bullet], ...
                     [q_bullet, qp_bullet]);
                 
    % Speed to derivative coordinates conversion
    D_circ = subs(mechanism.eqdyn.D_circ, ...
                  mechanism.eqdyn.q_circ, ...
                  q_bullet);
    
    Dp_circ = subs(mechanism.eqdyn.Dp_circ, ...
                   [mechanism.eqdyn.q_circ, ...
                    mechanism.eqdyn.qp_circ], ...
                   [q_circ, qp_circ]);
end