function A = ConstraintMatrix(in1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.

%    06-Nov-2020 18:23:22



delta_i = in1(4,:);

delta_o = in1(5,:);

theta = in1(3,:);

t2 = tan(delta_i);

t3 = tan(delta_o);

t4 = t2.*(3.0./2.0);

t5 = delta_i+theta;

t6 = cos(delta_i);

t7 = sin(t5);

t8 = cos(t5);

t9 = sin(delta_i);

A = reshape([0.0,0.0,0.0,t8,-t7,0.0,0.0,0.0,t7,t8,0.0,0.0,0.0,t6.*(-9.0./2.0)+t9.*(3.0./4.0),t6.*(3.0./4.0)+t9.*(9.0./2.0),(t3.*(3.0./2.0)-9.0./2.0).*(t2.^2+1.0).*(-2.0./9.0),0.0,0.0,0.0,0.0,(t3.^2+1.0).*(t4+9.0./2.0).*(-2.0./9.0),0.0,0.0,0.0,0.0,0.0,0.0,1.0./t6,-3.442462000000001e-1,0.0,0.0,0.0,(t4-9.0)./(cos(delta_o).*(t4+9.0)),0.0,0.0,0.0,t2.*(-1.0./3.0)-1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[5,9]);

end