function qp = KinematicVector(in1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.

%    20-Dec-2020 21:40:25



p1 = in1(4,:);

p2 = in1(5,:);

theta = in1(3,:);

qp = [p1.*cos(theta);p1.*sin(theta);p2];

end