function out1 = slidingfun(u)
%SLIDINGFUN
%    OUT1 = SLIDINGFUN(P1,P2,P2_D,X1,X2,X1_D,X2_D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    04-Sep-2019 08:11:36

x1 = u(1);
x2 = u(2);
p1 = u(3);
p2 = u(4);

x1_d = u(5);
x2_d = u(6);
p1_d = u(7);
p2_d = u(8);

out1 = p1.*1.959698194110669e-1-p2.*3.804208905044948e-3-p2_d.*1.921656105060219e-1+x1.*9.798490970553345e-1-x1_d.*9.798490970553345e-1+sqrt(6.77e2).*(x2-x2_d).*(1.0./6.77e2);
