function C_1delta = C_matrix(x, kappa_1, kappa_2, alpha_1, alpha_2, L, R, w)
%KINEMATICMATRIX
%    C_1DELTA = KINEMATICMATRIX(L,R,ALPHA_1,ALPHA_2,DELTA_I,DELTA_O,KAPPA_1,KAPPA_2,THETA,W)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Oct-2020 13:31:27

    x_pos =  x(1);
    y_pos =  x(2);
    theta =  x(3);

    delta_i = x(4);
    delta_o = x(5);

    phi_i = x(6);
    phi_l = x(7);
    phi_o = x(8);
    phi_r = x(9);

    t2 = tan(delta_i);
    t3 = delta_i+theta;
    t4 = cos(t3);
    t5 = t2.*w;
    t6 = L+t5;
    t7 = 1.0./t6;
    t8 = t2.*t7;
    t9 = tan(t8);
    t10 = L.^2;
    t11 = L.*t9;
    t12 = atan(t11);
    t13 = t12+theta;
    t14 = cos(t13);
    t15 = t9.^2;
    t16 = t10.*t15;
    t17 = t16+1.0;
    t18 = sqrt(t17);
    t19 = sin(t3);
    t20 = tan(alpha_1);
    t21 = cos(delta_i);
    t22 = tan(alpha_2);
    t23 = sin(delta_i);
    t24 = delta_o+theta;
    t25 = sin(t24);
    t26 = cos(delta_o);
    t27 = sin(delta_o);
    t28 = sin(t13);
    t29 = t14.^2;
    t30 = t28.^2;
    t31 = cos(t24);
    t32 = L.*t4.*t28.*2.0;
    t33 = t4.*t14.*w;
    t34 = t19.*t28.*w;
    t35 = L.*t18.*t23.*t29.*2.0;
    t36 = L.*t18.*t23.*t30.*2.0;
    t37 = t18.*t21.*t29.*w;
    t38 = t18.*t21.*t30.*w;
    t39 = L.*kappa_1.*t4.*t14.*t20.*2.0;
    t40 = kappa_2.*t4.*t22.*t31.*w;
    t41 = L.*kappa_1.*t19.*t20.*t28.*2.0;
    t42 = kappa_1.*t14.*t19.*t20.*w;
    t43 = kappa_2.*t19.*t22.*t25.*w;
    t44 = L.*t4.*t9.*t28.*w;
    t45 = kappa_1.*t4.*t9.*t10.*t20.*t28.*2.0;
    t46 = kappa_1.*t18.*t20.*t23.*t29.*w;
    t47 = kappa_1.*t18.*t20.*t23.*t30.*w;
    t48 = L.*kappa_1.*t4.*t9.*t14.*t20.*w;
    t49 = L.*kappa_1.*t9.*t19.*t20.*t28.*w;
    t50 = L.*kappa_1.*kappa_2.*t4.*t20.*t22.*t25.*2.0;
    t51 = L.*kappa_2.*t4.*t14.*t18.*t22.*t26.*2.0;
    t52 = L.*kappa_2.*t4.*t18.*t22.*t26.*t28.*2.0;
    t53 = L.*kappa_2.*t14.*t18.*t22.*t23.*t31.*2.0;
    t54 = kappa_1.*kappa_2.*t19.*t20.*t22.*t31.*w;
    t55 = L.*kappa_2.*t14.*t18.*t22.*t23.*t25.*2.0;
    t56 = L.*kappa_2.*t18.*t19.*t22.*t26.*t28.*2.0;
    t57 = kappa_2.*t14.*t18.*t21.*t22.*t31.*w;
    t58 = L.*kappa_2.*t18.*t22.*t23.*t25.*t28.*2.0;
    t59 = kappa_2.*t4.*t14.*t18.*t22.*t27.*w;
    t60 = kappa_2.*t14.*t18.*t21.*t22.*t25.*w;
    t61 = kappa_2.*t4.*t18.*t22.*t27.*t28.*w;
    t62 = kappa_2.*t18.*t21.*t22.*t25.*t28.*w;
    t63 = kappa_2.*t18.*t19.*t22.*t27.*t28.*w;
    t64 = kappa_1.*kappa_2.*t4.*t9.*t10.*t20.*t22.*t25.*2.0;
    t65 = kappa_1.*kappa_2.*t4.*t14.*t18.*t20.*t22.*t27.*w;
    t66 = kappa_1.*kappa_2.*t14.*t18.*t20.*t22.*t23.*t31.*w;
    t67 = kappa_1.*kappa_2.*t14.*t18.*t19.*t20.*t22.*t27.*w;
    t68 = kappa_1.*kappa_2.*t14.*t18.*t20.*t22.*t23.*t25.*w;
    t69 = kappa_1.*kappa_2.*t18.*t19.*t20.*t22.*t27.*t28.*w;
    t70 = kappa_1.*kappa_2.*t18.*t20.*t22.*t23.*t25.*t28.*w;
    t71 = L.*kappa_1.*kappa_2.*t4.*t9.*t20.*t22.*t25.*w;
    t72 = L.*kappa_1.*kappa_2.*t4.*t14.*t18.*t20.*t22.*t26.*2.0;
    t73 = L.*kappa_1.*kappa_2.*t18.*t20.*t21.*t22.*t28.*t31.*2.0;
    t74 = L.*kappa_1.*kappa_2.*t14.*t18.*t19.*t20.*t22.*t26.*2.0;
    t75 = L.*kappa_1.*kappa_2.*t18.*t19.*t20.*t22.*t26.*t28.*2.0;
    t78 = L.*t14.*t19.*2.0;
    t79 = t4.*t9.*t10.*t14.*2.0;
    t80 = t9.*t10.*t19.*t28.*2.0;
    t81 = L.*kappa_2.*t4.*t22.*t31.*2.0;
    t82 = L.*kappa_2.*t19.*t22.*t25.*2.0;
    t83 = kappa_1.*t4.*t20.*t28.*w;
    t84 = L.*t9.*t14.*t19.*w;
    t85 = kappa_1.*t9.*t10.*t14.*t19.*t20.*2.0;
    t86 = kappa_2.*t9.*t10.*t19.*t22.*t25.*2.0;
    t87 = L.*kappa_1.*t18.*t20.*t21.*t29.*2.0;
    t88 = L.*kappa_1.*t18.*t20.*t21.*t30.*2.0;
    t89 = kappa_2.*t4.*t9.*t10.*t22.*t31.*2.0;
    t90 = L.*kappa_2.*t4.*t9.*t22.*t31.*w;
    t91 = L.*kappa_2.*t9.*t19.*t22.*t25.*w;
    t92 = L.*kappa_1.*kappa_2.*t19.*t20.*t22.*t31.*2.0;
    t93 = L.*kappa_2.*t14.*t18.*t19.*t22.*t26.*2.0;
    t94 = kappa_1.*kappa_2.*t4.*t20.*t22.*t25.*w;
    t95 = L.*kappa_2.*t18.*t22.*t23.*t28.*t31.*2.0;
    t96 = kappa_2.*t18.*t21.*t22.*t28.*t31.*w;
    t97 = kappa_2.*t14.*t18.*t19.*t22.*t27.*w;
    t98 = kappa_1.*kappa_2.*t9.*t10.*t19.*t20.*t22.*t31.*2.0;
    t99 = kappa_1.*kappa_2.*t4.*t18.*t20.*t22.*t27.*t28.*w;
    t100 = kappa_1.*kappa_2.*t18.*t20.*t22.*t23.*t28.*t31.*w;
    t101 = L.*kappa_1.*kappa_2.*t9.*t19.*t20.*t22.*t31.*w;
    t102 = L.*kappa_1.*kappa_2.*t14.*t18.*t20.*t21.*t22.*t31.*2.0;
    t103 = L.*kappa_1.*kappa_2.*t4.*t18.*t20.*t22.*t26.*t28.*2.0;
    t104 = L.*kappa_1.*kappa_2.*t14.*t18.*t20.*t21.*t22.*t25.*2.0;
    t105 = L.*kappa_1.*kappa_2.*t18.*t20.*t21.*t22.*t25.*t28.*2.0;
    t76 = t32+t33+t34+t35+t36+t37+t38+t39+t40+t41+t42+t43+t44+t45+t46+t47+t48+t49+t50+...
          t51+t52+t53+t54+t55+t56+t57+t58+t59+t60+t61+t62+t63+t64+t65+t66+t67+t68+t69+...
          t70+t71+t72+t73+t74+t75-t78-t79-t80-t81-t82-t83-t84-t85-t86-t87-t88-t89-t90-...
          t91-t92-t93-t94-t95-t96-t97-t98-t99-t100-t101-t102-t103-t104-t105;
    t77 = 1.0./t76;
    t106 = t4.^2;
    t107 = t19.^2;
    C_1delta = reshape([0.0,0.0,0.0,-(t6.*t17)./(L.*(t2.^2+1.0).*(t9.*w-1.0)),...
                        1.0,0.0,0.0,0.0,0.0,...
                        t77.*(R.*t4.*w-R.*t4.*t9.*t10.*2.0+L.*R.*t14.*t18.*t23.*2.0+R.*kappa_1.*t19.*t20.*w+R.*t14.*t18.*t21.*w-R.*kappa_1.*t9.*t10.*t19.*t20.*2.0+L.*R.*kappa_2.*t4.*t18.*t22.*t26.*2.0-L.*R.*kappa_1.*t14.*t18.*t20.*t21.*2.0+L.*R.*kappa_2.*t18.*t22.*t23.*t25.*2.0+R.*kappa_2.*t4.*t18.*t22.*t27.*w+R.*kappa_1.*t14.*t18.*t20.*t23.*w+R.*kappa_2.*t18.*t21.*t22.*t25.*w+L.*R.*kappa_1.*kappa_2.*t18.*t19.*t20.*t22.*t26.*2.0-L.*R.*kappa_1.*kappa_2.*t18.*t20.*t21.*t22.*t25.*2.0+R.*kappa_1.*kappa_2.*t18.*t19.*t20.*t22.*t27.*w+R.*kappa_1.*kappa_2.*t18.*t20.*t22.*t23.*t25.*w), ...
                        t77.*(R.*t19.*w-R.*t9.*t10.*t19.*2.0+L.*R.*t18.*t23.*t28.*2.0-R.*kappa_1.*t4.*t20.*w+R.*t18.*t21.*t28.*w+R.*kappa_1.*t4.*t9.*t10.*t20.*2.0+L.*R.*kappa_2.*t18.*t19.*t22.*t26.*2.0-L.*R.*kappa_1.*t18.*t20.*t21.*t28.*2.0-L.*R.*kappa_2.*t18.*t22.*t23.*t31.*2.0+R.*kappa_2.*t18.*t19.*t22.*t27.*w+R.*kappa_1.*t18.*t20.*t23.*t28.*w-R.*kappa_2.*t18.*t21.*t22.*t31.*w-L.*R.*kappa_1.*kappa_2.*t4.*t18.*t20.*t22.*t26.*2.0+L.*R.*kappa_1.*kappa_2.*t18.*t20.*t21.*t22.*t31.*2.0-R.*kappa_1.*kappa_2.*t4.*t18.*t20.*t22.*t27.*w-R.*kappa_1.*kappa_2.*t18.*t20.*t22.*t23.*t31.*w), ...
                        R.*t18.*t77.*(t4.*t28-t14.*t19+kappa_1.*t4.*t14.*t20-kappa_2.*t4.*t22.*t31+kappa_1.*t19.*t20.*t28-kappa_2.*t19.*t22.*t25+kappa_1.*kappa_2.*t4.*t20.*t22.*t25-kappa_1.*kappa_2.*t19.*t20.*t22.*t31).*-2.0, ...
                        0.0, 0.0,t77.*(kappa_1.*t20+1.0).*(t106.*w+t107.*w-t9.*t10.*t106.*2.0-t9.*t10.*t107.*2.0+L.*t4.*t14.*t18.*t23.*2.0+L.*t4.*t18.*t21.*t28.*2.0-L.*t14.*t18.*t19.*t21.*2.0+L.*t18.*t19.*t23.*t28.*2.0+t4.*t14.*t18.*t21.*w-t4.*t18.*t23.*t28.*w+t14.*t18.*t19.*t23.*w+t18.*t19.*t21.*t28.*w+kappa_2.*t18.*t22.*t27.*t106.*w+kappa_2.*t18.*t22.*t27.*t107.*w+L.*kappa_2.*t18.*t22.*t26.*t106.*2.0+L.*kappa_2.*t18.*t22.*t26.*t107.*2.0+L.*kappa_2.*t4.*t18.*t22.*t23.*t25.*2.0-L.*kappa_2.*t4.*t18.*t21.*t22.*t31.*2.0-L.*kappa_2.*t18.*t19.*t21.*t22.*t25.*2.0-L.*kappa_2.*t18.*t19.*t22.*t23.*t31.*2.0+kappa_2.*t4.*t18.*t21.*t22.*t25.*w+kappa_2.*t4.*t18.*t22.*t23.*t31.*w+kappa_2.*t18.*t19.*t22.*t23.*t25.*w-kappa_2.*t18.*t19.*t21.*t22.*t31.*w), ...
                        1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,L.*t7,1.0], ...
                        [9,3]);
