function [f, f_i, f_ni] = fs_vectors(q, p, C_fric, M, sqrt_M, inv_M, M_12, Q, A_1delta, Ap_1delta, C_1delta, Cp_1delta)
%INPUTMATRIX
%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Oct-2020 13:53:49

    b_1delta = -Ap_1delta*C_1delta*p;
    
    % Useful constraint    
    B_1delta = A_1delta*M_12;
    pB_1delta = pinv(B_1delta);
    
    % ideal constraint
    a = inv_M*Q;
    
    Qc_i = sqrt_M*pB_1delta*(b_1delta - A_1delta*a);    
        
    n = length(pB_1delta);    
    Wc = eye(n) - pB_1delta*B_1delta;
    
    F = sqrt_M*Wc*M_12;
    Qc_ni = F*C_fric;
    
    f = C_1delta.'*Q;
    f_i = -C_1delta.'*M*Cp_1delta*p + C_1delta.'*Qc_i; 
    f_ni = C_1delta.'*Wc*C_fric;
end