symb = {'L01cg', 'L02cg', 'L03cg', ...
        'L11cg', 'L12cg', 'L13cg', ...
        'L21cg', 'L22cg', 'L23cg', ...
        'L01', 'L02', 'L03', ...
        'L11', 'L12', 'L13', ...
        'L21', 'L22', 'L23', ...
        'Le1', 'Le2', 'Le3', ...
        'deltaecg', 'Lecg', ...      
        'beta1', 'beta2', 'beta3', ...
        'gamma1', 'gamma2', 'gamma3', ...
        'm11', 'm12', 'm13', ...
        'm21', 'm22', 'm23', 'me', ...
        'J11', 'J12', 'J13', ...
        'J21', 'J22', 'J23', 'Je', ... 
        '\mathrm{xpp}', '\mathrm{ypp}', '\mathrm{alphapp}', ...
        '\mathrm{xp}', '\mathrm{yp}', '\mathrm{alphap}', ...
        'y\!\left(t\right)', 'y\!\left(t\right)', '\mathrm{\alpha}'...       
        '\mathrm{th11pp}', '\mathrm{th12pp}', '\mathrm{th13pp}', ...
        '\mathrm{th11p}', '\mathrm{th12p}', '\mathrm{th13p}', ...
        '\mathrm{th11}', '\mathrm{th12}', '\mathrm{th13}', ...
        '\mathrm{th21pp}', '\mathrm{th22pp}', '\mathrm{th23pp}', ...
        '\mathrm{th21p}', '\mathrm{th22p}', '\mathrm{th23p}', ...
        '\mathrm{th21}', '\mathrm{th22}', '\mathrm{th23}', ...
        '\!\left(t\right)'};


latexvar = {'\mathrm{L_{01}^{cg}}', '\mathrm{L_{02}^{cg}}', ...
            '\mathrm{L_{03}^{cg}}', ...
            '\mathrm{L_{11}^{cg}}', '\mathrm{L_{12}^{cg}}', ...
            '\mathrm{L_{13}^{cg}}', ...
            '\mathrm{L_{21}^{cg}}', '\mathrm{L_{22}^{cg}}', ...
            '\mathrm{L_{23}^{cg}}', ...
            '\mathrm{L_{01}}', '\mathrm{L_{02}}', ...
            '\mathrm{L_{03}}', ...
            '\mathrm{L_{11}}', '\mathrm{L_{12}}', ...
            '\mathrm{L_{13}}', ...
            '\mathrm{L_{21}}', '\mathrm{L_{22}}', '\mathrm{L_{23}}', ...
            '\mathrm{L_{e_1}}', '\mathrm{L_{e_2}}', '\mathrm{L_{e_3}}', ...
            '\mathrm{\delta_{e}^{cg}}', '\mathrm{L_{e}^{cg}}', ...
            '\mathrm{\beta_1}', '\mathrm{\beta_2}', '\mathrm{\beta_3}', ...
            '\mathrm{\gamma_1}', '\mathrm{\gamma_2}', '\mathrm{\gamma_3}', ...
            '\mathrm{m_{11}}', '\mathrm{m_{12}}', '\mathrm{m_{13}}', ...
            '\mathrm{m_{21}}', '\mathrm{m_{22}}', '\mathrm{m_{23}}', '\mathrm{m_e}', ...
            '\mathrm{J_{11}}', '\mathrm{J_{12}}', '\mathrm{J_{13}}', ...
            '\mathrm{J_{21}}', '\mathrm{J_{22}}', '\mathrm{J_{23}}', '\mathrm{J_e}', ... 
            '\mathrm{\ddot x}', '\mathrm{\ddot y}', '\mathrm{\ddot \alpha}', ...
            '\mathrm{\dot x}', '\mathrm{\dot y}', '\mathrm{\dot \alpha}', ...
            '\mathrm{x}', '\mathrm{y}', '\mathrm{alpha}', ...
            '\mathrm{\ddot \theta_{11}}', '\mathrm{\ddot \theta_{12}}', '\mathrm{\ddot \theta_{13}}', ...
            '\mathrm{\dot \theta_{11}}', '\mathrm{\dot \theta_{12}}', '\mathrm{\dot \theta_{13}}', ...
            '\mathrm{\theta_{11}}', '\mathrm{\theta_{12}}', '\mathrm{\theta_{13}}', ...
            '\mathrm{\ddot \theta_{21}}', '\mathrm{\ddot \theta_{22}}', '\mathrm{\ddot \theta_{23}}', ...
            '\mathrm{\dot \theta_{21}}', '\mathrm{\dot \theta_{22}}', '\mathrm{\dot \theta_{23}}', ...
            '\mathrm{\theta_{21}}', '\mathrm{\theta_{22}}', '\mathrm{\theta_{23}}', ''};


% Latex pretty model
pretty_str = latex_model(eqdyn, symb, latexvar);

% Save on file
fid = fopen('pretty_model.txt','wt');
fprintf(fid, '%s', pretty_str);
fclose(fid);