function dq = plant_vector(q, p, f_i_ni, C_1delta, inv_H)
% MASSMATRIX
%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Oct-2020 11:55:07
    
    dq = [C_1delta*p; inv_H*f_i_ni];
end