function u = control_handler(t, q_p, ...
                             sestimation_info, ...
                             trajectory_info, ...
                             control_info, sys)
                         
    xhat = source_estimation(t, q_p, sestimation_info, sys);                         
    u = run_cotrol_law(t, q_p, xhat, ...
                       sestimation_info, ...
                       control_info, ...
                       trajectory_info, sys);
end