function u = control_handler(t, q_p, source_reference, xhat_0, ...
                             nu, sigma, lambda, zeta, eta, oracle,  ...   
                             T, Q, P, sys)
    [xhat, xhat_1] = source_estimation(t, q_p, xhat_0, nu, sigma, ...
                                       lambda, oracle, T, ...
                                       source_reference, sys);
                                      
    u = ljapunov_based(t, q_p, xhat, xhat_1, Q, P, ...
                       zeta, eta, source_reference, sys);
end