function u = control_handler(t, q_p, source_reference, xhat_0, ...
                             nu, sigma, lambda, zeta, eta, oracle,  ...   
                             T, perc, P, degree, sys)
    xhat = source_estimation(t, q_p, xhat_0, nu, sigma, ...
                             lambda, oracle, T, ...
                             source_reference, sys);
    
    u = ljapunov_based(t, q_p, xhat, xhat_0, P, zeta, eta, ...
                       T, perc, degree, source_reference, sys);
end