function u = control_handler(t, q_p, source_reference, xhat_0, ...
                             nu, sigma, lambda, zeta, eta, oracle,  ...   
                             T, P, degree_G, W, sys)
    xhat = source_estimation(t, q_p, xhat_0, nu, sigma, ...
                             lambda, oracle, T, ...
                             source_reference, sys);
                         
    u = ljapunov_based(t, q_p, xhat, xhat_0, P, zeta, eta, ...
                       T, degree_G, W, source_reference, sys);
end