function qp = KinematicVector(t, in2)
%KINEMATICVECTOR
%    QP = KINEMATICVECTOR(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Oct-2020 15:40:43

delta_i = in2(4,:);
delta_o = in2(5,:);
p1 = in2(10,:);
p2 = in2(11,:);
p3 = in2(12,:);
p4 = in2(13,:);
theta = in2(3,:);
t2 = cos(delta_i);
t3 = cos(theta);
t4 = t3.*(9.0./2.0);
t5 = sin(theta);
t6 = t5.*(3.0./4.0);
t7 = delta_i.*2.0;
t8 = t7+theta;
t9 = cos(delta_o);
t10 = 1.0./t9;
t11 = t2.*9.0;
t12 = sin(delta_i);
t13 = t12.*(3.0./2.0);
t14 = t11+t13;
t15 = 1.0./t14;
t16 = sin(t8);
t17 = t3.*(3.0./4.0);
t18 = t5.*(9.0./2.0);
t19 = cos(t8);
t20 = delta_o.*2.0;
qp = [p1.*(t4+t6)+p3.*t2.*t10.*t15.*(t4+t6-t16.*(3.0./4.0)+t19.*(9.0./2.0)).*3.442462000000001e-1;
     -p1.*(t17-t18)+p3.*t2.*t10.*t15.*(t16.*(9.0./2.0)-t17+t18+t19.*(3.0./4.0)).*3.442462000000001e-1;
     p1;
     (p2.*(cos(t7).*(9.0./2.0)+sin(t7).*(3.0./2.0)+9.0./2.0))./(cos(t20).*(9.0./2.0)-sin(t20).*(3.0./2.0)+9.0./2.0);
     p2;p3.*t2.*t10.*t15.*(t11-t13);p3;(p4.*(9.0./2.0))./(tan(delta_i).*(3.0./2.0)+9.0./2.0);
     p4];
