
paths = {'car_model/Vehicle/Steering_model/Auxiliary_matrices/C_p', ...
         'car_model/Vehicle/Steering_model/Auxiliary_matrices/Q', ...
         'car_model/Vehicle/Steering_model/Auxiliary_matrices/C_1delta', ...
         'car_model/Vehicle/Steering_model/Auxiliary_matrices/dC_1delta', ...
         'car_model/Vehicle/Steering_model/Auxiliary_matrices/dA_1delta', ...
         'car_model/Vehicle/Steering_model/Friction_model', ...
         'car_model/Vehicle/Steering_model/Efforts', ...
         'car_model/Vehicle/Steering_model/H/Efforts'};
     
     
block = sf.find('Path', ,'-isa','Stateflow.EMChart');
