function plant = plantfun(u)
%PLANTFUN
%    PLANT = PLANTFUN(P1,P2,U,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    04-Sep-2019 07:31:42

x1 = u(1);
x2 = u(2);
p1 = u(3);
p2 = u(4);
u = u(5);

plant = [p1;p2;x1.*-2.0+x2;u+x1-x2];
